### ISSUE TITLE
Stack overflow

### ISSUE THREAD

**Issue by RoDmitry** [udoprog/fixed-map#52]
[Test case](https://github.com/RoDmitry/fixed-map/blob/stack_overflow/tests/map_in_map.rs)

thread 'big' has overflowed its stack
fatal runtime error: stack overflow

**Comment by udoprog** [comment]
I believe the issue here is that the storage generated won't be sparse, in fact it will be the number of variants in `Script` times the number of variants in `Language` (`324 * 169`) since you are constructing a `Map<Script, Map<Language, Vec<u32>>`. This 
is not very space efficient. The size of the vector itself would be 24 bytes (on a 64-bit machine), resulting in at least `54756 * 24 = 1314144` bytes. Possibly more since the inner map is probably aligned. The default stack size on Windows for example is 1MB. I believe it's a bit more on Linux.

You are more likely to be looking for a map which allocates sparsely (like `HashMap<K, T>`, rather than one which stores data as an array. I don't think there is much that can be done here.

**Comment by RoDmitry** [comment]
I do understand that, just experimenting. And I have found a solution to use Box: `Map<Script, Box<Map<Language, Vec<u32>>>`, but not so sure about it's performance.
